version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 29093:29093
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS:
         EXTERNAL_SAME_HOST://:29092,
         EXTERNAL_DIFFERENT_HOST://:29093,
         INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS:
         INTERNAL://kafka:9092,
         EXTERNAL_SAME_HOST://localhost:29092,
         EXTERNAL_DIFFERENT_HOST://161.54.37.188:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
         INTERNAL:PLAINTEXT,
         EXTERNAL_SAME_HOST:PLAINTEXT,
         EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 12

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

networks:
  broker-kafka:
    driver: bridge

volumes:
  kafka-data:
    driver: local
