version: '3.8'
services:

  neo4j:
    image: neo4j:community
    hostname: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_apoc_uuid_enabled: "true"
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_allow__upgrade: "true"
      NEO4J_dbms_default__database: "neo4j"
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_dbms_logs_debug_level: DEBUG

  search:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - search:/data.ms

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

  cache:
    image: redis:6.2.6-alpine
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASSWORD}
    volumes:
      - cache:/data

volumes:
  search:
    driver: local
  cache:
    driver: local
  neo4jdata:
    driver: local

