CREATE CONSTRAINT ON (p:Person) ASSERT p.id IS UNIQUE
CREATE CONSTRAINT ON (p:Person) ASSERT p.email IS UNIQUE
CREATE CONSTRAINT ON (o:Organization) ASSERT o.id IS UNIQUE
CREATE CONSTRAINT ON (t:team) ASSERT t.id IS UNIQUE
