version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/srv:/srv
      - $PWD/ssl:/root/certs
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
